version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/api/Dockerfile
      
  database:
    image: 'postgres:latest'
    container_name: todo-database